execute:
    freeze: auto

project:
  type: website
  output-dir: _site
  #author: "Thomas M. Rudolf"

website:
  title: "HOME" #"Automatation and Industrial Robots"
  
  navbar:
    left:
      - href: index.qmd
  sidebar:
    style: 'docked'
    search: true
    contents:
      - section: Index (2024-3)
        href: index.qmd
        contents: 
        -  index.qmd
      - section: Indroduction
        href: chapter01.qmd
        contents: 
        - chapter01.qmd
      - section: Chapter 2
        href: chapter02.qmd
        contents: 
        - chapter02.qmd
      - section: Chapter 3
        href: chapter03.qmd
        contents: 
        - chapter03.qmd
      - section: Chapter 4
        href: chapter04.qmd
        contents: 
        - chapter04.qmd
      - section: Chapter 5
        href: chapter05.qmd
        contents: 
        - chapter05.qmd
      - section: Chapter 6
        href: chapter06.qmd
        contents: 
        - chapter06.qmd
      - section: about
        href: about.qmd
        contents: 
        - about.qmd
      
format:
  html:
    theme: default
    #output-file: index.html
    css: style.css
    toc: false
    toc-location: left
    toc-depth: 3


editor: visual

