project:
  type: website

output-dir: ./

website:
  title: "HOME" #"Automatation and Industrial Robots"
  navbar:
    left:
      - href: index.qmd
  sidebar:
    style: 'docked'
    search: true
    contents:
      #- section: Index (2024-3)
      #  href: index.qmd
      - section: Indroduction
        #href: ./chapters/chapter01.qmd
        contents: 
        - ./chapters/chapter01.qmd
      - section: Chapter 2
        href: ./chapters/chapter02.qmd
        contents: 
        - ./chapters/chapter02.qmd
      - section: Chapter 3
        href: ./chapters/chapter03.qmd
        contents: 
        - ./chapters/chapter03.qmd
      - section: Chapter 4
        href: ./chapters/chapter04.qmd
        contents: 
        - ./chapters/chapter04.qmd
      - section: Chapter 5
        href: ./chapters/chapter05.qmd
        contents: 
        - ./chapters/chapter05.qmd
      - section: Chapter 6
        href: ./chapters/chapter06.qmd
        contents: 
        - ./chapters/chapter06.qmd
      - section: about
        href: about.qmd
        contents: 
        - about.qmd
      
format:
  html:
    #theme: cosmo
    output-file: index.html
    css: style.css
    toc: false
    toc-location: left
    toc-depth: 3


editor: visual

