execute:
  freeze: auto

project:
  type: book
  output-dir: docs
book:
  title: "Automation and Industrial Robots"
  author: "Thomas M. Rudolf"
  chapters:
    - index.qmd
    - chapter00.qmd
    - part: "Chapters"
      chapters:
        - chapter01.qmd
        - chapter02.qmd
        - chapter03.qmd
        - chapter04.qmd
        - chapter05.qmd
        - chapter06.qmd
    - part: "About"
      chapters:
        - about.qmd

  
  sidebar:
    numbered: false
    style: docked
    search: true
    contents:
      - section: Index (2024-3)
        contents: 
          - index.qmd
      - section: About the lecture
        contents: 
          - chapter00.qmd
      - section: Chapter 1
        contents: 
          - chapter01.qmd
      - section: Chapter 2
        contents: 
          - chapter02.qmd
          - #exc_chapter02.qmd
      - section: Chapter 3
        contents: 
          - chapter03.qmd
          - #chapter03.qmd #exc_chapter03.qmd
      - section: Chapter 4
        contents: 
          - chapter04.qmd
      - section: Chapter 5
        contents: 
          - chapter05.qmd
      - section: Chapter 6
        contents: 
          - chapter06.qmd
      - section: About
        contents: 
          - about.qmd
format:
  html:
    theme: default
    css: style.css
    toc: false
    toc-location: left
    toc-depth: 3
editor: visual