---
title: "Thomas M. Rudolf"
author: "Thomas M. Rudolf"
format: html
editor: visual
---

# Biography

He is currently an full professor and researcher at ITAM. He completed his engineering studies with a specialization in Mechatronics at the University of Darmstadt. During his studies, he focused on the fundamentals of control theory, identification of systems and mechanics. After his studies in Darmstadt, he started working as a research assistant at the Laboratory of Machine Tools at the University of Aachen, RWTH Aachen.

During the following six years at the RWTH, he worked as a scientific assistant and development engineer. During this time, he worked on his doctoral investigation. Besides the investigation, his responsibilities also included the coordination and management of investigation projects. His doctoral thesis (Adaptable parametrization of diagnostic systems by using digital drive signals for process monitoring) was defended on the 11th of March 2014 with a presentation about “Systems Engineering for Medical Devices”.

He continued his professional carrier at Roche Diagnostics as a Systems Engineer with a focus on simulation and computation. His primary task was the physical modeling and calculation of insulin delivery systems in order to define technical requirements as well as to verify changes of specifications. This task also included DoE in order to find the most relevant system parameters, the tolerance analysis, and statistical evaluations applying Six Sigma methods, e.g. to evaluate the risks of new consumable products for medical devices. He also applied the methods of Six Sigma to develop a quality gate for the selection of sterile consumable products for medical devices.

He lectures Control Engineering, Manufacturing of Components, Computer Integrated Manufacturing, as well as a Solid Mechanics, Design of Robotics Mechanisms, and Mechatronics Systems. He published several articles in international journals about diagnostics and monitoring of manufacturing processes.
