name: Quarto Publish
on:
  #workflow_dispatch:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version:  "1.6.33"
      - name: Render project
        uses: quarto-dev/quarto-actions/render@v2
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
